name: easy_resend
description: A Dart package for easy integration with the Easy Resend API to send emails with attachments.
version: 1.0.2
repository: https://github.com/dylanroman03/Easy_Resend

environment:
  sdk: ">=2.19.0 <4.0.0"

# Add regular dependencies here.

# dependencies:
  # path: ^1.8.0

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0
dependencies:
  http: ^1.2.0

topics: 
  - email
  - resend
  - dart
  - api